name: Docker Image CI

on:
  push:
    branches: ["main"]

env:
  SYSDIG_URL: https://us2.app.sysdig.com
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }} --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Download Sysdig Secure Inline Scan - New
        run: |
          curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"

      - name: Set Permissions Sysdig Secure Inline Scan - New
        run: |
          chmod +x ./sysdig-cli-scanner

      - name: Scan Image Sysdig Secure Inline Scan - New
        env:
          SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }}
        run: ./sysdig-cli-scanner --apiurl ${{env.SYSDIG_URL}} --full-vulns-table docker://${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the Docker image
        run: docker push -a ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
